using Saxon.Api;

namespace AltovaGen.Engine.Saxon;

/// <summary>
/// The default <see cref="IExtensionFunctionRegistry"/>. It registers the managed,
/// COM-free <c>evaluate()</c> bridge under every namespace URI Altova tools use for that
/// function, so stylesheets generated by XMLSpy, StyleVision, MapForce and RaptorXML
/// resolve their dynamic-expression calls without an Altova runtime.
/// </summary>
/// <remarks>
/// <list type="bullet">
///   <item><c>http://www.altova.com/xslt-extensions</c> — the canonical
///     <c>altova:evaluate()</c> namespace.</item>
///   <item><c>http://www.altova.com</c> — used by some Altova-generated stylesheets
///     that declare <c>xmlns:altova="http://www.altova.com"</c>.</item>
///   <item><c>http://www.altova.com/StyleVision/user-xpath-functions</c> — the
///     StyleVision user-function namespace (<c>sps:evaluate()</c>).</item>
/// </list>
/// Only <c>evaluate()</c> is provided: other Altova/XBRL/StyleVision functions require an
/// XBRL taxonomy that no free processor carries and therefore fail with XPST0017, which is
/// reported with a clear message by <see cref="SaxonXsltEngine"/>.
/// </remarks>
internal sealed class SaxonExtensionFunctionRegistry : IExtensionFunctionRegistry
{
    /// <summary>The canonical Altova XSLT extension namespace.</summary>
    public const string AltovaExtensionsNamespace = "http://www.altova.com/xslt-extensions";

    /// <summary>The Altova generic namespace.</summary>
    public const string AltovaNamespace = "http://www.altova.com";

    /// <summary>The StyleVision user-XPath-functions namespace.</summary>
    public const string StyleVisionNamespace = "http://www.altova.com/StyleVision/user-xpath-functions";

    private readonly IReadOnlyList<ExtensionFunctionDefinition> _functions =
    [
        new AltovaEvaluateFunction(AltovaExtensionsNamespace),
        new AltovaEvaluateFunction(AltovaNamespace),
        new AltovaEvaluateFunction(StyleVisionNamespace),

        // Managed, COM-free emulations of the Altova XSLT 2.0 utility functions,
        // registered under the canonical xslt-extensions namespace.
        new AltovaDistinctNodesFunction(AltovaExtensionsNamespace),
        new AltovaGetTempFolderFunction(AltovaExtensionsNamespace),
        new AltovaEncodeForRftFunction(AltovaExtensionsNamespace)
    ];

    public IReadOnlyList<ExtensionFunctionDefinition> Functions => _functions;
}
